name: Testing Package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python3 -

      - name: Configure Poetry
        run: poetry config virtualenvs.create false

      - name: Install dependencies
        run: poetry install

      - name: Set up .env file
        run: | 
          echo "SELECTEL_USERNAME=${{ secrets.SELECTEL_USERNAME }}" >> .env
          echo "SELECTEL_ACCOUNT_ID=${{ secrets.SELECTEL_ACCOUNT_ID }}" >> .env
          echo "SELECTEL_PASSWORD=${{ secrets.SELECTEL_PASSWORD }}" >> .env


      - name: Run tests
        run: poetry run pytest
